name: Update Pinboard Wizard Cask

on:
  repository_dispatch:
    types: [update-cask]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to update to (e.g., v0.2.0)"
        required: true
        type: string
      download_url:
        description: "Download URL override (optional)"
        required: false
        type: string
      sha256:
        description: "SHA256 override (optional)"
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  update-cask:
    runs-on: macos-latest
    steps:
      - name: Checkout tap repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git user
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Resolve inputs (version/url/sha256)
        id: vars
        run: |
          set -euo pipefail
          if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            VERSION="${{ github.event.client_payload.version }}"
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
          fi
          if [[ -z "${VERSION}" ]]; then
            echo "Missing version"; exit 1
          fi
          VERSION_NUMBER="${VERSION#v}"

          if [[ -n "${{ github.event.client_payload.download_url }}" ]]; then
            DOWNLOAD_URL="${{ github.event.client_payload.download_url }}"
          elif [[ -n "${{ github.event.inputs.download_url }}" ]]; then
            DOWNLOAD_URL="${{ github.event.inputs.download_url }}"
          else
            DOWNLOAD_URL="https://github.com/RikuVan/pinboard_wizard/releases/download/v${VERSION_NUMBER}/pinboard-wizard-v${VERSION_NUMBER}-macos.tar.gz"
          fi

          if [[ -n "${{ github.event.client_payload.sha256 }}" ]]; then
            SHA256="${{ github.event.client_payload.sha256 }}"
          elif [[ -n "${{ github.event.inputs.sha256 }}" ]]; then
            SHA256="${{ github.event.inputs.sha256 }}"
          else
            echo "Computing SHA256 from ${DOWNLOAD_URL} ..."
            curl -L -o artifact.tar.gz "$DOWNLOAD_URL"
            SHA256=$(shasum -a 256 artifact.tar.gz | awk '{print $1}')
            rm -f artifact.tar.gz
          fi

          echo "version_number=$VERSION_NUMBER" >> "$GITHUB_ENV"
          echo "download_url=$DOWNLOAD_URL"   >> "$GITHUB_ENV"
          echo "sha256=$SHA256"               >> "$GITHUB_ENV"

      - name: Update cask file
        run: |
          set -euo pipefail
          FILE="Casks/pinboard-wizard.rb"

          sed -i "" "s/^  version .*/  version '${{ env.version_number }}'/" "$FILE"
          sed -i "" "s/^  sha256 .*/  sha256 '${{ env.sha256 }}'/" "$FILE"
          sed -i "" "s|^  url .*|  url '${{ env.download_url }}'|" "$FILE"

          echo "Updated Cask:"
          cat "$FILE"

      - name: Link local repo as tap
        run: |
          set -euo pipefail
          brew tap --custom-remote rikuvan/formulae "$PWD"

      - name: Validate cask (fetch & audit)
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          brew fetch --cask --force rikuvan/formulae/pinboard-wizard
          brew audit --cask --online --strict rikuvan/formulae/pinboard-wizard

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          commit-message: "pinboard-wizard: update to v${{ env.version_number }}"
          title: "pinboard-wizard: update to v${{ env.version_number }}"
          body: |
            Update pinboard-wizard cask to version **${{ env.version_number }}**.

            - URL: ${{ env.download_url }}
            - SHA256: `${{ env.sha256 }}`

            Automated PR.
          branch: update/pinboard-wizard-v${{ env.version_number }}
          delete-branch: true
          add-paths: |
            Casks/pinboard-wizard.rb
